version: "3"

services:
  hub:
    image: selenium/hub
    networks:
      - selenium
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome-debug
    networks:
      - selenium
    depends_on:
      - hub
    ports:
      - 5900
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444

  firefox:
    image: selenium/node-firefox-debug
    networks:
      - selenium
    depends_on:
      - hub
    ports:
      - 5900
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444

networks:
  selenium:
    driver: bridge
